### ISSUE TITLE
Bootstrap 4 beta

### ISSUE THREAD

**Issue by wderzawiec** [bootstrapthemesco/bootstrap-4-multi-dropdown-navbar#1]
Really love this, but am trying with latest Bootstrap 4.0 beta and the clickable version is not working, the first Submenu under the "Dropdown Link" closes when you click on it. Will there be an update? Thank you.

**Comment by Ataurr** [comment]
It's work fine with new version alpha 6. Update your Bootstrap version. https://v4-alpha.getbootstrap.com/

**Comment by MGeurts** [comment]
Nice solution. But this is not working on latest v4.0.0-beta.2
The navbar is in "mobile mode", even on large screen.
And it does not react to mouse action.

**Comment by Ataurr** [comment]
https://github.com/bootstrapthemesco/bootstrap-4-multi-dropdown-navbar/releases/tag/beta2.0
