### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by bjenmonk** [bootstrapthemesco/bootstrap-4-multi-dropdown-navbar#12]
Please add search functionality, icons at the end of each menu, menu header

**Comment by Ataurr** [comment]
Send pull request with search

**Comment by bjenmonk** [comment]
![image](https://user-images.githubusercontent.com/768956/53343400-531fd100-38de-11e9-9da8-57f4f81883f2.png)
something like this

**Comment by bjenmonk** [comment]
> Send pull request with search

Sorry, my css and js knowledge is very less.
