### ISSUE TITLE
Bootstrap 4.3.1

### ISSUE THREAD

**Issue by TechBill** [bootstrapthemesco/bootstrap-4-multi-dropdown-navbar#14]
This doesn't work on latest Bootstrap 4.3.1

**Comment by professorSchiggy** [comment]
Same for v4.4.1

**Comment by N6REJ** [comment]
following, I found the same issue.

**Comment by quique** [comment]
Can you elaborate on what exactly is not working?

I just installed it with Bootstrap 4.4.1, and on my laptop seems to work fine.

**Comment by N6REJ** [comment]
wow, 8 months for a response? jeeez
