### ISSUE TITLE
(Suggestions) Change the arrow when an item is expanded

### ISSUE THREAD

**Issue by egkareem** [bootstrapthemesco/bootstrap-4-multi-dropdown-navbar#9]
Nice tool. Few suggestions (not really an issue)
1. Tell the user how to show the colors of sub-menu items
2. When an item is expanded, change the arrow from down to right (maybe)
3. Place license file as in License.txt

Thank you for a good software.

**Comment by Ataurr** [comment]
@egkareem Send pull request.

**Comment by ferleysilva** [comment]
.
